### ISSUE TITLE
Check support for BBB 2.3

### ISSUE THREAD

**Issue by bennyboer** [bennyboer/bbb_app#192]
Since BBB 2.3 is out, we should check what needs to be done to support it.

**Comment by freehussain** [comment]
hello,

i just tried it, it has the following issues:

1- connect audio issue( delay, try to reconnect not working)
2- share screen never success 


i just tried it on android 11

**Comment by freehussain** [comment]
log from android studio:

W/FlutterJNI( 1311): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: com.changjoopark.flutter_foreground_plugin/callback. Response ID: 0
W/FlutterJNI( 1311): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: com.changjoopark.flutter_foreground_plugin/callback. Response ID: 0
W/FlutterJNI( 1311): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: com.changjoopark.flutter_foreground_plugin/callback. Response ID: 0
W/FlutterJNI( 1311): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: com.changjoopark.flutter_foreground_plugin/callback. Response ID: 0
W/FlutterJNI( 1311): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: com.changjoopark.flutter_foreground_plugin/callback. Response ID: 0
I/CameraManagerGlobal( 1311): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_OPEN for client com.samsung.adaptivebrightnessgo API Level 2
W/FlutterJNI( 1311): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: com.changjoopark.flutter_foreground_plugin/callback. Response ID: 0
I/CameraManagerGlobal( 1311): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_ACTIVE for client com.samsung.adaptivebrightnessgo API Level 2
I/CameraManagerGlobal( 1311): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_IDLE for client com.samsung.adaptivebrightnessgo API Level 2
I/CameraManagerGlobal( 1311): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client com.samsung.adaptivebrightnessgo API Level 2
W/FlutterJNI( 1311): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: com.changjoopark.flutter_foreground_plugin/callback. Response ID: 0
W/FlutterJNI( 1311): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: com.changjoopark.flutter_foreground_plugin/callback. Response ID: 0
W/FlutterJNI( 1311): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: com.changjoopark.flutter_foreground_plugin/callback. Response ID: 0
W/FlutterJNI( 1311): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: com.changjoopark.flutter_foreground_plugin/callback. 


also another error:

 [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Bad state: No element
E/flutter ( 1311): #0      ListQueue.first (dart:collection/queue.dart:621:25)
E/flutter ( 1311): #1      ScaffoldState.showSnackBar.<anonymous closure> (package:flutter/src/material/scaffold.dart:1726:27)
E/flutter ( 1311): #2      _StartViewState._joinMeeting (package:bbb_app/src/view/start/start_view.dart:463:29)
E/flutter ( 1311): #3      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 1311): #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 1311): #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter ( 1311): #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter ( 1311): #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter ( 1311): #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter ( 1311): #9      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
E/flutter ( 1311): #10     _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 1311): #11     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 1311): #12     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 1311): #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 1311): #14     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 1311): #15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter ( 1311):

**Comment by bennyboer** [comment]
Thanks for checking!

**Comment by ciftcisamet** [comment]
Can't connect the audio and trying to reconnect is not working. Is there anyone who could solve this problem?

**Comment by bennyboer** [comment]
Not at the moment - since busy - but I will check around july

**Comment by ciftcisamet** [comment]
> hello,
> 
> i just tried it, it has the following issues:
> 
> 1- connect audio issue( delay, try to reconnect not working)
> 2- share screen never success
> 
> i just tried it on android 11

Hi,

What's your bbb server version? And could you solve this problem?

**Comment by freehussain** [comment]
hello @ciftcisamet 

it's version 2.3

**Comment by bennyboer** [comment]
Waiting for https://github.com/bigbluebutton/bigbluebutton/issues/12762
